sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '123456'

  alioss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tDc4pGNmNo1out5z9Fe
    accessKeySecret: kc0gXnYOeJrbcYXoZ4mrO4xEApa6rj
    bucketName: sky-take-out-show

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 10

  wechat:
    appid: wx2ee5dbb5c9efc135
    secret: ae615817cddea7a8ad7fb0131f60ee76